Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -11,15 +11,20 @@ jobs:
 
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
 
       - name: Install Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '18'  # Use a Node.js version compatible with clasp
+          node-version: '17'  # Use a Node.js version compatible with clasp
 
       - name: Install clasp
         run: npm install -g @google/clasp
+
+      - name: Debug clasp
+        run: |
+          echo $CLASP_PASSWORD
+          clasp login --no-localhost || echo "Login failed!"
 
       - name: Authenticate clasp
         run: |
